services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NODE_VERSION: 20
        JWTSECRET: ${JWTSECRET}
        DB_HOST: db
        DB_PORT: 3306
        DB_USER: root
        DB_PASSWORD: root
        DB_NAME: test_cursor
    command: ["npm", "run", "dev"]
    working_dir: /app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NEXT_TELEMETRY_DISABLED: "1"
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_NAME: test_cursor
      DB_PASSWORD: root
      DB_ROOT_PASSWORD: root
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - next_cache:/app/.next
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: db-dev-cursor
    environment:
      MYSQL_DATABASE: test_cursor
      # MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

volumes:
  node_modules:
  next_cache:
  db_data:

